### PR TITLE
Expose preferredDatePickerStyle on XLFormDateCell and set wheel as default

### PR DESCRIPTION
**Pull request by robmaceachern**

### CODE REVIEW

**Review by zbencz3 — APPROVED** [review]
Looks good! Good catch @robmaceachern 
<details>

Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-13 at 01 45 13
</details>

**Comment by zbencz3** [comment]
Actually it seems there is a problem when you select the [admission date from the patient card screen](https://github.com/bil0-dr-bill/drbill-ios/blob/d676a22f0b37d220d3667bc246e7f94bc3f3cef0/Dr.%20Bill/DBDateField.m#L63-L79), but that's not an XLForm thing, so we need to deal with it through a different [PR](https://github.com/bil0-dr-bill/drbill-ios/pull/1782).
<details>

Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-13 at 01 50 29
</details>

**Comment by robmaceachern** [comment]
Yeah I’ll open up another PR for the pod update and that one (it’s not XLForm-related).

**Comment by zbencz3** [comment]
@robmaceachern I created one [here](https://github.com/bil0-dr-bill/drbill-ios/pull/1782).

**Pull request merged**
